"""GIDL onset ablation on the 2D NMOS (configs/input_mosfet_2d_btbt.yaml):
why does GIDL appear so late in Vg here, when in modern MOSFETs it picks up
right below threshold? Starting from the baseline device, one modern feature
is added per step (cumulative), and Id-Vg at Vds = 1 V is re-run with the
nonlocal tunneling model (btbt/paths2d.py: field-line Kane + Hurkx):

  0 baseline      3 nm SiO2, n+ poly gate (4.05 eV), 40 nm overlap of a
                  uniform n 3e18 tip, abrupt step to n+ 1e20
  1 + EOT 1 nm    the same 3 nm layer as a high-k with EOT 1 nm
                  (eps_r = 11.7): 3x the gate capacitance, same mesh
  2 + metal gate  workfunction 4.3 eV (typical n-type metal gate) instead
                  of n+ poly
  3 + graded S/D  the S/D become 1e20 boxes with an exponential tail
                  (3 nm/decade laterally, 5 nm/decade vertically): the
                  junction sits ~10 nm under the gate, and the gate edge
                  sees every doping from 1e20 down to the body's 1e18.
                  No halo (rare in FinFET/nanosheet devices).
  4 + interface traps  N_it = 5e11 cm^-2 midgap traps at the Si/SiO2
                  interface, with field-enhanced (Hurkx) capture: trap-
                  assisted tunneling needing only ~Eg/2 of band bending

All variants share one mesh setup (a 2 nm refine box at the drain gate edge
is added to every variant). The variant configs are written to
out/btbt/gidl_ablation/ next to the results.

Usage: python3 -m btbt.gidl_ablation [--workers N]
"""
import argparse
import copy
import csv
import os
import time
from concurrent.futures import ProcessPoolExecutor

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import yaml

from btbt import main_btbt2d_sweep as M

ROOT = M.ROOT
BASE = os.path.join(ROOT, "configs", "input_mosfet_2d_btbt.yaml")
OUT = os.path.join(ROOT, "out", "btbt", "gidl_ablation")
MAP_VG = -1.0
COLORS = ["#6c757d", "#1f6feb", "#2f9e44", "#e8590c", "#d6336c"]


def variants():
    base = M.load_config(BASE)
    base["mesh"]["refine_boxes"] = list(base["mesh"].get("refine_boxes") or []) + [
        dict(name="drain_gate_edge", x_range_um=[0.77, 0.83], y_range_um=[0.0, 0.02], h_um=0.002)]
    out = []
    c = copy.deepcopy(base)
    out.append(("0 baseline: 3 nm SiO2, n+ poly, 40 nm uniform 3e18 tip", copy.deepcopy(c)))
    for r in c["geometry"]["regions"]:
        if r.get("kind") == "insulator":
            r["eps_r"] = 11.7
    out.append(("1 + EOT 1 nm (3 nm high-k, k = 11.7)", copy.deepcopy(c)))
    c["gate"]["workfunction_eV"] = 4.3
    out.append(("2 + metal gate, 4.3 eV", copy.deepcopy(c)))
    oxide = [r for r in c["geometry"]["regions"] if r.get("kind") == "insulator"]
    c["geometry"]["regions"] = [
        dict(name="source", doping_type="n", concentration_cm3=1.0e20, x_range_um=[0.0, 0.304],
             y_range_um=[0.0, 0.14], grading_nm_per_decade=[3.0, 5.0]),
        dict(name="drain", doping_type="n", concentration_cm3=1.0e20, x_range_um=[0.796, 1.1],
             y_range_um=[0.0, 0.14], grading_nm_per_decade=[3.0, 5.0]),
    ] + oxide
    out.append(("3 + graded S/D (3 nm/dec, ~10 nm overlap), no halo", copy.deepcopy(c)))
    c.setdefault("btbt", {})["interface_traps"] = dict(Nit_cm2=5e11, sigma_cm2=1e-15, vth_cm_s=1e7)
    out.append(("4 + interface traps (Nit = 5e11 cm^-2, Hurkx-enhanced)", copy.deepcopy(c)))
    return out


def onset(vg, idd):
    """GIDL onset: the Vg (below the current minimum) where |Id| has risen
    to 10x its minimum, interpolated in log(Id)."""
    a = np.abs(idd)
    k = int(np.argmin(a))
    lo = a[k]
    for j in range(k, 0, -1):
        if a[j - 1] >= 10 * lo:
            f = (np.log10(10 * lo) - np.log10(a[j])) / (np.log10(a[j - 1]) - np.log10(a[j]))
            return vg[j] + f * (vg[j - 1] - vg[j])
    return np.nan


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=5)
    args = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    vs = variants()
    tasks = []
    for k, (label, cfg) in enumerate(vs):
        path = os.path.join(OUT, f"variant{k}.yaml")
        with open(path, "w") as f:
            f.write(f"# GIDL ablation variant {k}: {label}\n# generated by btbt/gidl_ablation.py\n")
            yaml.safe_dump(cfg, f, sort_keys=False)
        b = cfg["btbt"]
        vgs = M._grid(b["vgs_start_V"], b["vgs_stop_V"], b["vgs_step_V"])
        tasks.append(dict(kind="idvg", model="nonlocal", Vds=float(b["vds_V"]), values=vgs, map_at=[MAP_VG],
                          config=path))
    for var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "VECLIB_MAXIMUM_THREADS", "MKL_NUM_THREADS"):
        os.environ[var] = "1"
    t0 = time.perf_counter()
    with ProcessPoolExecutor(max_workers=min(args.workers, len(tasks))) as pool:
        results = list(pool.map(M.run_curve, tasks))
    print(f"{len(tasks)} variants: {time.perf_counter() - t0:.1f}s wall-clock")

    fig, axes = plt.subplots(1, 3, figsize=(21, 6.2))
    rows = []
    with open(os.path.join(OUT, "gidl_ablation.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["variant", "Vg_V", "Id_A_per_um", "kane_surface", "tat_surface", "it_surface", "kane_bulk",
                    "tat_bulk"])
        for k, ((label, _), res) in enumerate(zip(vs, results)):
            pts = res["points"]
            n_ok = sum(p["res_norm"] < 1e-4 for p in pts.values())
            v = np.array(sorted(pts))
            c = {key: np.array([pts[x][key] for x in v]) for key in next(iter(pts.values()))}
            for i, x in enumerate(v):
                w.writerow([k, f"{x:.3f}"] + [f"{c[key][i]:.6e}" for key in
                                              ("drain", "kane_surface", "tat_surface", "it_surface", "kane_bulk",
                                               "tat_bulk")])
            vo = onset(v, c["drain"])
            gate_edge = c["kane_surface"] + c["tat_surface"] + c["it_surface"]
            rows.append((label, n_ok, len(v), vo, np.interp(-1.0, v, np.abs(c["drain"])),
                         np.interp(-2.0, v, np.abs(c["drain"])), np.min(np.abs(c["drain"]))))
            axes[0].semilogy(v, np.abs(c["drain"]), "o-", ms=3, color=COLORS[k], label=label)
            if np.isfinite(vo):
                axes[0].axvline(vo, color=COLORS[k], lw=0.8, ls=":")
            axes[1].semilogy(v, np.where(gate_edge > 0, gate_edge, np.nan), "-", color=COLORS[k], label=label)
            mp = res["maps"].get(MAP_VG)
            if mp is not None:
                ctx = M._context(tasks[k]["config"])
                g = ctx["geom"]
                info = mp["gen"].get("kane") if mp["gen"] else None
                cut = 0.79
                if info is not None and len(info["pair"]):
                    surf = g.points[info["start"], 1] < M.SURFACE_DEPTH
                    if surf.any():
                        j = np.flatnonzero(surf)[np.argmax(info["pair"][surf])]
                        cut = g.points[info["start"][j], 0] * 1e4
                yc = np.linspace(0.0, 0.04, 400)
                cc = M._cut(ctx, mp, cut, yc)
                axes[2].plot(yc * 1e3, cc["Ec"], "-", color=COLORS[k], label=f"{label.split(':')[0]}: x = {cut:.3f} um")
                axes[2].plot(yc * 1e3, cc["Ev"], "-", color=COLORS[k])
    axes[0].set_xlabel("Vg (V)"); axes[0].set_ylabel("|Id| (A/um)")
    axes[0].set_title("NMOS Id-Vg, Vds = 1 V (nonlocal Kane + Hurkx); dotted = GIDL onset (10x Id,min)")
    axes[0].grid(alpha=0.3, which="both"); axes[0].legend(fontsize=7.5, loc="upper center")
    axes[1].set_xlabel("Vg (V)"); axes[1].set_ylabel("q x gate-edge generation, drain side (A/um)")
    axes[1].set_title("gate-edge (surface) tunneling: Kane + trap-assisted + interface traps")
    axes[1].grid(alpha=0.3, which="both"); axes[1].legend(fontsize=7.5)
    axes[2].set_xlabel("depth below the gate oxide (nm)"); axes[2].set_ylabel("energy (eV)")
    axes[2].set_title(f"bands through the strongest GIDL spot, Vg = {MAP_VG:g} V (Ec upper, Ev lower)")
    axes[2].grid(alpha=0.3); axes[2].legend(fontsize=7.5)
    fig.tight_layout()
    fig.savefig(os.path.join(OUT, "gidl_ablation.png"), dpi=130); plt.close(fig)
    print(f"\n{'variant':58s} {'conv':>6} {'onset Vg':>9} {'Id(-1V)':>10} {'Id(-2V)':>10} {'Id,min':>10}")
    for label, n_ok, n, vo, i1, i2, imin in rows:
        print(f"{label:58s} {n_ok:>3}/{n:<2} {vo:9.2f} {i1:10.2e} {i2:10.2e} {imin:10.2e}")
    print(f"wrote {OUT}/gidl_ablation.png, gidl_ablation.csv")


if __name__ == "__main__":
    main()
